version: '3'
services:
  envoy:
    build:
      context: ./dash/
      dockerfile: ./Dockerfile
    image: dash
    ports:
      - "8080:8080"
  
  rust:
    image: rust:latest
    tty: true
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
 