# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import things_pb2 as things__pb2


class ImageStreamerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamImages = channel.unary_stream(
                '/ImageStreamer/StreamImages',
                request_serializer=things__pb2.Empty.SerializeToString,
                response_deserializer=things__pb2.Image.FromString,
                )


class ImageStreamerServicer(object):
    """The greeting service definition.
    """

    def StreamImages(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamImages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamImages,
                    request_deserializer=things__pb2.Empty.FromString,
                    response_serializer=things__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageStreamer(object):
    """The greeting service definition.
    """

    @staticmethod
    def StreamImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ImageStreamer/StreamImages',
            things__pb2.Empty.SerializeToString,
            things__pb2.Image.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
